language: java
sudo: false

addons:
  sonarcloud:
    organization: "wojciechzankowski-github"

jdk:
  - openjdk8
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
